apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
      # with and without
        autoscaling.knative.dev/minScale: "1"
    spec:
      securityContext:
        seccompProfile:
          type: "RuntimeDefault"    
      containers:
        - image: docker.io/openshift/hello-openshift
          env:
            - name: RESPONSE 
              value: "Hello Serverless!"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile: 
              type: "RuntimeDefault"
            capabilities:
              drop: ["ALL"]
# Add seccomp for queue proxy container